//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("EncuestasModel", "FK_Canton_Provincia", "Provincia", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EncuestasC.Models.Provinciax), "Canton", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EncuestasC.Models.Cantonx))]
[assembly: EdmRelationshipAttribute("EncuestasModel", "FK_CPSP_Canton", "Canton", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EncuestasC.Models.Cantonx), "CPSP", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EncuestasC.Models.CPSPx))]
[assembly: EdmRelationshipAttribute("EncuestasModel", "FK_Distrito_Canton", "Canton", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EncuestasC.Models.Cantonx), "Distrito", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EncuestasC.Models.Distritox))]
[assembly: EdmRelationshipAttribute("EncuestasModel", "FK_Poblado_Canton", "Canton", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EncuestasC.Models.Cantonx), "Poblado", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EncuestasC.Models.Pobladox))]
[assembly: EdmRelationshipAttribute("EncuestasModel", "FK_Encuesta_CodigoPresupuestario", "CodigoPresupuestario", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EncuestasC.Models.CodigoPresupuestariox), "Encuesta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EncuestasC.Models.Encuestax))]
[assembly: EdmRelationshipAttribute("EncuestasModel", "FK_CPSP_Distrito", "Distrito", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EncuestasC.Models.Distritox), "CPSP", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EncuestasC.Models.CPSPx))]
[assembly: EdmRelationshipAttribute("EncuestasModel", "FK_CPSP_Poblado", "Poblado", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EncuestasC.Models.Pobladox), "CPSP", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EncuestasC.Models.CPSPx))]
[assembly: EdmRelationshipAttribute("EncuestasModel", "FK_CPSP_Provincia", "Provincia", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EncuestasC.Models.Provinciax), "CPSP", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EncuestasC.Models.CPSPx))]
[assembly: EdmRelationshipAttribute("EncuestasModel", "FK_Email_CPSP", "CPSP", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EncuestasC.Models.CPSPx), "Email", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EncuestasC.Models.Emailx))]
[assembly: EdmRelationshipAttribute("EncuestasModel", "FK_Encuesta_CPSP", "CPSP", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EncuestasC.Models.CPSPx), "Encuesta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EncuestasC.Models.Encuestax))]
[assembly: EdmRelationshipAttribute("EncuestasModel", "FK_Telefono_CPSP", "CPSP", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EncuestasC.Models.CPSPx), "Telefono", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EncuestasC.Models.Telefonox))]
[assembly: EdmRelationshipAttribute("EncuestasModel", "FK_Distrito_Provincia", "Provincia", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EncuestasC.Models.Provinciax), "Distrito", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EncuestasC.Models.Distritox))]
[assembly: EdmRelationshipAttribute("EncuestasModel", "FK_Poblado_Distrito", "Distrito", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EncuestasC.Models.Distritox), "Poblado", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EncuestasC.Models.Pobladox))]
[assembly: EdmRelationshipAttribute("EncuestasModel", "FK_Encuesta_Email", "Email", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EncuestasC.Models.Emailx), "Encuesta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EncuestasC.Models.Encuestax))]
[assembly: EdmRelationshipAttribute("EncuestasModel", "FK_Encuesta_EstadoServicio", "EstadoServicio", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EncuestasC.Models.EstadoServiciox), "Encuesta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EncuestasC.Models.Encuestax))]
[assembly: EdmRelationshipAttribute("EncuestasModel", "FK_Encuesta_Proyecto", "Proyecto", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EncuestasC.Models.Proyectox), "Encuesta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EncuestasC.Models.Encuestax))]
[assembly: EdmRelationshipAttribute("EncuestasModel", "FK_Encuesta_Telefono", "Telefono", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EncuestasC.Models.Telefonox), "Encuesta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EncuestasC.Models.Encuestax))]
[assembly: EdmRelationshipAttribute("EncuestasModel", "FK_Poblado_Provincia", "Provincia", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EncuestasC.Models.Provinciax), "Poblado", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EncuestasC.Models.Pobladox))]

#endregion

namespace EncuestasC.Models
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class EncuestasEntitiesx : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto EncuestasEntitiesx usando la cadena de conexión encontrada en la sección 'EncuestasEntitiesx' del archivo de configuración de la aplicación.
        /// </summary>
        public EncuestasEntitiesx() : base("name=EncuestasEntitiesx", "EncuestasEntitiesx")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto EncuestasEntitiesx.
        /// </summary>
        public EncuestasEntitiesx(string connectionString) : base(connectionString, "EncuestasEntitiesx")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto EncuestasEntitiesx.
        /// </summary>
        public EncuestasEntitiesx(EntityConnection connection) : base(connection, "EncuestasEntitiesx")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Cantonx> Canton
        {
            get
            {
                if ((_Canton == null))
                {
                    _Canton = base.CreateObjectSet<Cantonx>("Canton");
                }
                return _Canton;
            }
        }
        private ObjectSet<Cantonx> _Canton;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<CodigoPresupuestariox> CodigoPresupuestario
        {
            get
            {
                if ((_CodigoPresupuestario == null))
                {
                    _CodigoPresupuestario = base.CreateObjectSet<CodigoPresupuestariox>("CodigoPresupuestario");
                }
                return _CodigoPresupuestario;
            }
        }
        private ObjectSet<CodigoPresupuestariox> _CodigoPresupuestario;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<CPSPx> CPSP
        {
            get
            {
                if ((_CPSP == null))
                {
                    _CPSP = base.CreateObjectSet<CPSPx>("CPSP");
                }
                return _CPSP;
            }
        }
        private ObjectSet<CPSPx> _CPSP;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Distritox> Distrito
        {
            get
            {
                if ((_Distrito == null))
                {
                    _Distrito = base.CreateObjectSet<Distritox>("Distrito");
                }
                return _Distrito;
            }
        }
        private ObjectSet<Distritox> _Distrito;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Emailx> Email
        {
            get
            {
                if ((_Email == null))
                {
                    _Email = base.CreateObjectSet<Emailx>("Email");
                }
                return _Email;
            }
        }
        private ObjectSet<Emailx> _Email;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Encuestax> Encuesta
        {
            get
            {
                if ((_Encuesta == null))
                {
                    _Encuesta = base.CreateObjectSet<Encuestax>("Encuesta");
                }
                return _Encuesta;
            }
        }
        private ObjectSet<Encuestax> _Encuesta;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<EstadoServiciox> EstadoServicio
        {
            get
            {
                if ((_EstadoServicio == null))
                {
                    _EstadoServicio = base.CreateObjectSet<EstadoServiciox>("EstadoServicio");
                }
                return _EstadoServicio;
            }
        }
        private ObjectSet<EstadoServiciox> _EstadoServicio;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Pobladox> Poblado
        {
            get
            {
                if ((_Poblado == null))
                {
                    _Poblado = base.CreateObjectSet<Pobladox>("Poblado");
                }
                return _Poblado;
            }
        }
        private ObjectSet<Pobladox> _Poblado;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Provinciax> Provincia
        {
            get
            {
                if ((_Provincia == null))
                {
                    _Provincia = base.CreateObjectSet<Provinciax>("Provincia");
                }
                return _Provincia;
            }
        }
        private ObjectSet<Provinciax> _Provincia;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Proyectox> Proyecto
        {
            get
            {
                if ((_Proyecto == null))
                {
                    _Proyecto = base.CreateObjectSet<Proyectox>("Proyecto");
                }
                return _Proyecto;
            }
        }
        private ObjectSet<Proyectox> _Proyecto;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Telefonox> Telefono
        {
            get
            {
                if ((_Telefono == null))
                {
                    _Telefono = base.CreateObjectSet<Telefonox>("Telefono");
                }
                return _Telefono;
            }
        }
        private ObjectSet<Telefonox> _Telefono;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Canton. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCanton(Cantonx cantonx)
        {
            base.AddObject("Canton", cantonx);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet CodigoPresupuestario. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCodigoPresupuestario(CodigoPresupuestariox codigoPresupuestariox)
        {
            base.AddObject("CodigoPresupuestario", codigoPresupuestariox);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet CPSP. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCPSP(CPSPx cPSPx)
        {
            base.AddObject("CPSP", cPSPx);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Distrito. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToDistrito(Distritox distritox)
        {
            base.AddObject("Distrito", distritox);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Email. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEmail(Emailx emailx)
        {
            base.AddObject("Email", emailx);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Encuesta. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEncuesta(Encuestax encuestax)
        {
            base.AddObject("Encuesta", encuestax);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet EstadoServicio. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEstadoServicio(EstadoServiciox estadoServiciox)
        {
            base.AddObject("EstadoServicio", estadoServiciox);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Poblado. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPoblado(Pobladox pobladox)
        {
            base.AddObject("Poblado", pobladox);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Provincia. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToProvincia(Provinciax provinciax)
        {
            base.AddObject("Provincia", provinciax);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Proyecto. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToProyecto(Proyectox proyectox)
        {
            base.AddObject("Proyecto", proyectox);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet sysdiagrams. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Telefono. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTelefono(Telefonox telefonox)
        {
            base.AddObject("Telefono", telefonox);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EncuestasModel", Name="Cantonx")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cantonx : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Cantonx.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        public static Cantonx CreateCantonx(global::System.Decimal id)
        {
            Cantonx cantonx = new Cantonx();
            cantonx.Id = id;
            return cantonx;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Decimal _Id;
        partial void OnIdChanging(global::System.Decimal value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_Canton_Provincia", "Provincia")]
        public Provinciax Provincia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Provinciax>("EncuestasModel.FK_Canton_Provincia", "Provincia").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Provinciax>("EncuestasModel.FK_Canton_Provincia", "Provincia").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Provinciax> ProvinciaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Provinciax>("EncuestasModel.FK_Canton_Provincia", "Provincia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Provinciax>("EncuestasModel.FK_Canton_Provincia", "Provincia", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_CPSP_Canton", "CPSP")]
        public EntityCollection<CPSPx> CPSP
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CPSPx>("EncuestasModel.FK_CPSP_Canton", "CPSP");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CPSPx>("EncuestasModel.FK_CPSP_Canton", "CPSP", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_Distrito_Canton", "Distrito")]
        public EntityCollection<Distritox> Distrito
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Distritox>("EncuestasModel.FK_Distrito_Canton", "Distrito");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Distritox>("EncuestasModel.FK_Distrito_Canton", "Distrito", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_Poblado_Canton", "Poblado")]
        public EntityCollection<Pobladox> Poblado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Pobladox>("EncuestasModel.FK_Poblado_Canton", "Poblado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Pobladox>("EncuestasModel.FK_Poblado_Canton", "Poblado", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EncuestasModel", Name="CodigoPresupuestariox")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CodigoPresupuestariox : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto CodigoPresupuestariox.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        public static CodigoPresupuestariox CreateCodigoPresupuestariox(global::System.Decimal id)
        {
            CodigoPresupuestariox codigoPresupuestariox = new CodigoPresupuestariox();
            codigoPresupuestariox.Id = id;
            return codigoPresupuestariox;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Decimal _Id;
        partial void OnIdChanging(global::System.Decimal value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Codigo
        {
            get
            {
                return _Codigo;
            }
            set
            {
                OnCodigoChanging(value);
                ReportPropertyChanging("Codigo");
                _Codigo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Codigo");
                OnCodigoChanged();
            }
        }
        private Nullable<global::System.Decimal> _Codigo;
        partial void OnCodigoChanging(Nullable<global::System.Decimal> value);
        partial void OnCodigoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_Encuesta_CodigoPresupuestario", "Encuesta")]
        public EntityCollection<Encuestax> Encuesta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Encuestax>("EncuestasModel.FK_Encuesta_CodigoPresupuestario", "Encuesta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Encuestax>("EncuestasModel.FK_Encuesta_CodigoPresupuestario", "Encuesta", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EncuestasModel", Name="CPSPx")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CPSPx : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto CPSPx.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        public static CPSPx CreateCPSPx(global::System.Decimal id)
        {
            CPSPx cPSPx = new CPSPx();
            cPSPx.Id = id;
            return cPSPx;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Decimal _Id;
        partial void OnIdChanging(global::System.Decimal value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_CPSP_Canton", "Canton")]
        public Cantonx Canton
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cantonx>("EncuestasModel.FK_CPSP_Canton", "Canton").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cantonx>("EncuestasModel.FK_CPSP_Canton", "Canton").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cantonx> CantonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cantonx>("EncuestasModel.FK_CPSP_Canton", "Canton");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cantonx>("EncuestasModel.FK_CPSP_Canton", "Canton", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_CPSP_Distrito", "Distrito")]
        public Distritox Distrito
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Distritox>("EncuestasModel.FK_CPSP_Distrito", "Distrito").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Distritox>("EncuestasModel.FK_CPSP_Distrito", "Distrito").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Distritox> DistritoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Distritox>("EncuestasModel.FK_CPSP_Distrito", "Distrito");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Distritox>("EncuestasModel.FK_CPSP_Distrito", "Distrito", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_CPSP_Poblado", "Poblado")]
        public Pobladox Poblado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pobladox>("EncuestasModel.FK_CPSP_Poblado", "Poblado").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pobladox>("EncuestasModel.FK_CPSP_Poblado", "Poblado").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Pobladox> PobladoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pobladox>("EncuestasModel.FK_CPSP_Poblado", "Poblado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Pobladox>("EncuestasModel.FK_CPSP_Poblado", "Poblado", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_CPSP_Provincia", "Provincia")]
        public Provinciax Provincia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Provinciax>("EncuestasModel.FK_CPSP_Provincia", "Provincia").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Provinciax>("EncuestasModel.FK_CPSP_Provincia", "Provincia").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Provinciax> ProvinciaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Provinciax>("EncuestasModel.FK_CPSP_Provincia", "Provincia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Provinciax>("EncuestasModel.FK_CPSP_Provincia", "Provincia", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_Email_CPSP", "Email")]
        public EntityCollection<Emailx> Email
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Emailx>("EncuestasModel.FK_Email_CPSP", "Email");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Emailx>("EncuestasModel.FK_Email_CPSP", "Email", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_Encuesta_CPSP", "Encuesta")]
        public EntityCollection<Encuestax> Encuesta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Encuestax>("EncuestasModel.FK_Encuesta_CPSP", "Encuesta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Encuestax>("EncuestasModel.FK_Encuesta_CPSP", "Encuesta", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_Telefono_CPSP", "Telefono")]
        public EntityCollection<Telefonox> Telefono
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Telefonox>("EncuestasModel.FK_Telefono_CPSP", "Telefono");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Telefonox>("EncuestasModel.FK_Telefono_CPSP", "Telefono", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EncuestasModel", Name="Distritox")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Distritox : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Distritox.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        public static Distritox CreateDistritox(global::System.Decimal id)
        {
            Distritox distritox = new Distritox();
            distritox.Id = id;
            return distritox;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Decimal _Id;
        partial void OnIdChanging(global::System.Decimal value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_Distrito_Canton", "Canton")]
        public Cantonx Canton
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cantonx>("EncuestasModel.FK_Distrito_Canton", "Canton").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cantonx>("EncuestasModel.FK_Distrito_Canton", "Canton").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cantonx> CantonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cantonx>("EncuestasModel.FK_Distrito_Canton", "Canton");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cantonx>("EncuestasModel.FK_Distrito_Canton", "Canton", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_CPSP_Distrito", "CPSP")]
        public EntityCollection<CPSPx> CPSP
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CPSPx>("EncuestasModel.FK_CPSP_Distrito", "CPSP");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CPSPx>("EncuestasModel.FK_CPSP_Distrito", "CPSP", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_Distrito_Provincia", "Provincia")]
        public Provinciax Provincia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Provinciax>("EncuestasModel.FK_Distrito_Provincia", "Provincia").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Provinciax>("EncuestasModel.FK_Distrito_Provincia", "Provincia").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Provinciax> ProvinciaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Provinciax>("EncuestasModel.FK_Distrito_Provincia", "Provincia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Provinciax>("EncuestasModel.FK_Distrito_Provincia", "Provincia", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_Poblado_Distrito", "Poblado")]
        public EntityCollection<Pobladox> Poblado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Pobladox>("EncuestasModel.FK_Poblado_Distrito", "Poblado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Pobladox>("EncuestasModel.FK_Poblado_Distrito", "Poblado", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EncuestasModel", Name="Emailx")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Emailx : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Emailx.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        public static Emailx CreateEmailx(global::System.Decimal id)
        {
            Emailx emailx = new Emailx();
            emailx.Id = id;
            return emailx;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Decimal _Id;
        partial void OnIdChanging(global::System.Decimal value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Correo
        {
            get
            {
                return _Correo;
            }
            set
            {
                OnCorreoChanging(value);
                ReportPropertyChanging("Correo");
                _Correo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Correo");
                OnCorreoChanged();
            }
        }
        private global::System.String _Correo;
        partial void OnCorreoChanging(global::System.String value);
        partial void OnCorreoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_Email_CPSP", "CPSP")]
        public CPSPx CPSP
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CPSPx>("EncuestasModel.FK_Email_CPSP", "CPSP").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CPSPx>("EncuestasModel.FK_Email_CPSP", "CPSP").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CPSPx> CPSPReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CPSPx>("EncuestasModel.FK_Email_CPSP", "CPSP");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CPSPx>("EncuestasModel.FK_Email_CPSP", "CPSP", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_Encuesta_Email", "Encuesta")]
        public EntityCollection<Encuestax> Encuesta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Encuestax>("EncuestasModel.FK_Encuesta_Email", "Encuesta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Encuestax>("EncuestasModel.FK_Encuesta_Email", "Encuesta", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EncuestasModel", Name="Encuestax")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Encuestax : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Encuestax.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        public static Encuestax CreateEncuestax(global::System.Decimal id)
        {
            Encuestax encuestax = new Encuestax();
            encuestax.Id = id;
            return encuestax;
        }

        #endregion

        #region Propiedades primitivas

     

         
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Decimal _Id;
        partial void OnIdChanging(global::System.Decimal value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContestaLlamada
        {
            get
            {
                return _ContestaLlamada;
            }
            set
            {
                OnContestaLlamadaChanging(value);
                ReportPropertyChanging("ContestaLlamada");
                _ContestaLlamada = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContestaLlamada");
                OnContestaLlamadaChanged();
            }
        }
        private global::System.String _ContestaLlamada;
        partial void OnContestaLlamadaChanging(global::System.String value);
        partial void OnContestaLlamadaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NombreContacto
        {
            get
            {
                return _NombreContacto;
            }
            set
            {
                OnNombreContactoChanging(value);
                ReportPropertyChanging("NombreContacto");
                _NombreContacto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NombreContacto");
                OnNombreContactoChanged();
            }
        }
        private global::System.String _NombreContacto;
        partial void OnNombreContactoChanging(global::System.String value);
        partial void OnNombreContactoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comentarios
        {
            get
            {
                return _Comentarios;
            }
            set
            {
                OnComentariosChanging(value);
                ReportPropertyChanging("Comentarios");
                _Comentarios = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comentarios");
                OnComentariosChanged();
            }
        }
        private global::System.String _Comentarios;
        partial void OnComentariosChanging(global::System.String value);
        partial void OnComentariosChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_Encuesta_CodigoPresupuestario", "CodigoPresupuestario")]
        public CodigoPresupuestariox CodigoPresupuestario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CodigoPresupuestariox>("EncuestasModel.FK_Encuesta_CodigoPresupuestario", "CodigoPresupuestario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CodigoPresupuestariox>("EncuestasModel.FK_Encuesta_CodigoPresupuestario", "CodigoPresupuestario").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CodigoPresupuestariox> CodigoPresupuestarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CodigoPresupuestariox>("EncuestasModel.FK_Encuesta_CodigoPresupuestario", "CodigoPresupuestario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CodigoPresupuestariox>("EncuestasModel.FK_Encuesta_CodigoPresupuestario", "CodigoPresupuestario", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_Encuesta_CPSP", "CPSP")]
        public CPSPx CPSP
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CPSPx>("EncuestasModel.FK_Encuesta_CPSP", "CPSP").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CPSPx>("EncuestasModel.FK_Encuesta_CPSP", "CPSP").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CPSPx> CPSPReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CPSPx>("EncuestasModel.FK_Encuesta_CPSP", "CPSP");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CPSPx>("EncuestasModel.FK_Encuesta_CPSP", "CPSP", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_Encuesta_Email", "Email")]
        public Emailx Email
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Emailx>("EncuestasModel.FK_Encuesta_Email", "Email").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Emailx>("EncuestasModel.FK_Encuesta_Email", "Email").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Emailx> EmailReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Emailx>("EncuestasModel.FK_Encuesta_Email", "Email");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Emailx>("EncuestasModel.FK_Encuesta_Email", "Email", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_Encuesta_EstadoServicio", "EstadoServicio")]
        public EstadoServiciox EstadoServicio
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EstadoServiciox>("EncuestasModel.FK_Encuesta_EstadoServicio", "EstadoServicio").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EstadoServiciox>("EncuestasModel.FK_Encuesta_EstadoServicio", "EstadoServicio").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EstadoServiciox> EstadoServicioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EstadoServiciox>("EncuestasModel.FK_Encuesta_EstadoServicio", "EstadoServicio");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EstadoServiciox>("EncuestasModel.FK_Encuesta_EstadoServicio", "EstadoServicio", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_Encuesta_Proyecto", "Proyecto")]
        public Proyectox Proyecto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Proyectox>("EncuestasModel.FK_Encuesta_Proyecto", "Proyecto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Proyectox>("EncuestasModel.FK_Encuesta_Proyecto", "Proyecto").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Proyectox> ProyectoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Proyectox>("EncuestasModel.FK_Encuesta_Proyecto", "Proyecto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Proyectox>("EncuestasModel.FK_Encuesta_Proyecto", "Proyecto", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_Encuesta_Telefono", "Telefono")]
        public Telefonox Telefono
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Telefonox>("EncuestasModel.FK_Encuesta_Telefono", "Telefono").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Telefonox>("EncuestasModel.FK_Encuesta_Telefono", "Telefono").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Telefonox> TelefonoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Telefonox>("EncuestasModel.FK_Encuesta_Telefono", "Telefono");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Telefonox>("EncuestasModel.FK_Encuesta_Telefono", "Telefono", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EncuestasModel", Name="EstadoServiciox")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EstadoServiciox : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto EstadoServiciox.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        public static EstadoServiciox CreateEstadoServiciox(global::System.Decimal id)
        {
            EstadoServiciox estadoServiciox = new EstadoServiciox();
            estadoServiciox.Id = id;
            return estadoServiciox;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Decimal _Id;
        partial void OnIdChanging(global::System.Decimal value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Detalle
        {
            get
            {
                return _Detalle;
            }
            set
            {
                OnDetalleChanging(value);
                ReportPropertyChanging("Detalle");
                _Detalle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Detalle");
                OnDetalleChanged();
            }
        }
        private global::System.String _Detalle;
        partial void OnDetalleChanging(global::System.String value);
        partial void OnDetalleChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_Encuesta_EstadoServicio", "Encuesta")]
        public EntityCollection<Encuestax> Encuesta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Encuestax>("EncuestasModel.FK_Encuesta_EstadoServicio", "Encuesta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Encuestax>("EncuestasModel.FK_Encuesta_EstadoServicio", "Encuesta", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EncuestasModel", Name="Pobladox")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pobladox : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Pobladox.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        public static Pobladox CreatePobladox(global::System.Decimal id)
        {
            Pobladox pobladox = new Pobladox();
            pobladox.Id = id;
            return pobladox;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Decimal _Id;
        partial void OnIdChanging(global::System.Decimal value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_Poblado_Canton", "Canton")]
        public Cantonx Canton
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cantonx>("EncuestasModel.FK_Poblado_Canton", "Canton").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cantonx>("EncuestasModel.FK_Poblado_Canton", "Canton").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cantonx> CantonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cantonx>("EncuestasModel.FK_Poblado_Canton", "Canton");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cantonx>("EncuestasModel.FK_Poblado_Canton", "Canton", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_CPSP_Poblado", "CPSP")]
        public EntityCollection<CPSPx> CPSP
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CPSPx>("EncuestasModel.FK_CPSP_Poblado", "CPSP");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CPSPx>("EncuestasModel.FK_CPSP_Poblado", "CPSP", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_Poblado_Distrito", "Distrito")]
        public Distritox Distrito
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Distritox>("EncuestasModel.FK_Poblado_Distrito", "Distrito").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Distritox>("EncuestasModel.FK_Poblado_Distrito", "Distrito").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Distritox> DistritoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Distritox>("EncuestasModel.FK_Poblado_Distrito", "Distrito");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Distritox>("EncuestasModel.FK_Poblado_Distrito", "Distrito", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_Poblado_Provincia", "Provincia")]
        public Provinciax Provincia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Provinciax>("EncuestasModel.FK_Poblado_Provincia", "Provincia").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Provinciax>("EncuestasModel.FK_Poblado_Provincia", "Provincia").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Provinciax> ProvinciaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Provinciax>("EncuestasModel.FK_Poblado_Provincia", "Provincia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Provinciax>("EncuestasModel.FK_Poblado_Provincia", "Provincia", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EncuestasModel", Name="Provinciax")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Provinciax : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Provinciax.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        public static Provinciax CreateProvinciax(global::System.Decimal id)
        {
            Provinciax provinciax = new Provinciax();
            provinciax.Id = id;
            return provinciax;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Decimal _Id;
        partial void OnIdChanging(global::System.Decimal value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_Canton_Provincia", "Canton")]
        public EntityCollection<Cantonx> Canton
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cantonx>("EncuestasModel.FK_Canton_Provincia", "Canton");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cantonx>("EncuestasModel.FK_Canton_Provincia", "Canton", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_CPSP_Provincia", "CPSP")]
        public EntityCollection<CPSPx> CPSP
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CPSPx>("EncuestasModel.FK_CPSP_Provincia", "CPSP");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CPSPx>("EncuestasModel.FK_CPSP_Provincia", "CPSP", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_Distrito_Provincia", "Distrito")]
        public EntityCollection<Distritox> Distrito
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Distritox>("EncuestasModel.FK_Distrito_Provincia", "Distrito");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Distritox>("EncuestasModel.FK_Distrito_Provincia", "Distrito", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_Poblado_Provincia", "Poblado")]
        public EntityCollection<Pobladox> Poblado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Pobladox>("EncuestasModel.FK_Poblado_Provincia", "Poblado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Pobladox>("EncuestasModel.FK_Poblado_Provincia", "Poblado", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EncuestasModel", Name="Proyectox")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Proyectox : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Proyectox.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        public static Proyectox CreateProyectox(global::System.Decimal id)
        {
            Proyectox proyectox = new Proyectox();
            proyectox.Id = id;
            return proyectox;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Decimal _Id;
        partial void OnIdChanging(global::System.Decimal value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Detalle
        {
            get
            {
                return _Detalle;
            }
            set
            {
                OnDetalleChanging(value);
                ReportPropertyChanging("Detalle");
                _Detalle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Detalle");
                OnDetalleChanged();
            }
        }
        private global::System.String _Detalle;
        partial void OnDetalleChanging(global::System.String value);
        partial void OnDetalleChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_Encuesta_Proyecto", "Encuesta")]
        public EntityCollection<Encuestax> Encuesta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Encuestax>("EncuestasModel.FK_Encuesta_Proyecto", "Encuesta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Encuestax>("EncuestasModel.FK_Encuesta_Proyecto", "Encuesta", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EncuestasModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto sysdiagrams.
        /// </summary>
        /// <param name="name">Valor inicial de la propiedad name.</param>
        /// <param name="principal_id">Valor inicial de la propiedad principal_id.</param>
        /// <param name="diagram_id">Valor inicial de la propiedad diagram_id.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EncuestasModel", Name="Telefonox")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Telefonox : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Telefonox.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        public static Telefonox CreateTelefonox(global::System.Decimal id)
        {
            Telefonox telefonox = new Telefonox();
            telefonox.Id = id;
            return telefonox;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Decimal _Id;
        partial void OnIdChanging(global::System.Decimal value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Telefono1
        {
            get
            {
                return _Telefono1;
            }
            set
            {
                OnTelefono1Changing(value);
                ReportPropertyChanging("Telefono1");
                _Telefono1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Telefono1");
                OnTelefono1Changed();
            }
        }
        private Nullable<global::System.Decimal> _Telefono1;
        partial void OnTelefono1Changing(Nullable<global::System.Decimal> value);
        partial void OnTelefono1Changed();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_Telefono_CPSP", "CPSP")]
        public CPSPx CPSP
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CPSPx>("EncuestasModel.FK_Telefono_CPSP", "CPSP").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CPSPx>("EncuestasModel.FK_Telefono_CPSP", "CPSP").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CPSPx> CPSPReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CPSPx>("EncuestasModel.FK_Telefono_CPSP", "CPSP");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CPSPx>("EncuestasModel.FK_Telefono_CPSP", "CPSP", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncuestasModel", "FK_Encuesta_Telefono", "Encuesta")]
        public EntityCollection<Encuestax> Encuesta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Encuestax>("EncuestasModel.FK_Encuesta_Telefono", "Encuesta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Encuestax>("EncuestasModel.FK_Encuesta_Telefono", "Encuesta", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
